from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional


@dataclass
class AgentContext:
    """
    Shared execution context passed between all agents.

    This object stores conversation state, routing information,
    user preferences, and execution metadata.
    """

    # User information
    user_id: Optional[int] = None
    session_id: Optional[int] = None

    # Current request
    query: str = ""

    # Conversation history
    conversation: List[Dict[str, str]] = field(default_factory=list)

    # User preferences (theme, accessibility, etc.)
    preferences: Dict[str, Any] = field(default_factory=dict)

    # Intermediate outputs generated by agents
    memory: Dict[str, Any] = field(default_factory=dict)

    # Selected agent name
    active_agent: Optional[str] = None

    # Execution trace
    execution_log: List[str] = field(default_factory=list)

    # Request timestamp
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def log(self, message: str) -> None:
        """Append a message to the execution trace."""
        self.execution_log.append(message)

    def update_memory(self, key: str, value: Any) -> None:
        """Store intermediate data for downstream agents."""
        self.memory[key] = value

    def get_memory(self, key: str, default=None):
        """Retrieve stored intermediate data."""
        return self.memory.get(key, default)